name: CI/CD Deploy Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
      runs-on: ubuntu-latest 
      permissions:
        contents: read
        packages: write

      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }} 
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ghcr.io/${{ github.repository_owner }}/anrealshop-frontend:latest
  deploy:
      runs-on: ubuntu-latest
      needs: build-and-push 

      steps:
            - name: Deploy to DigitalOcean Droplet
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST_IP }} 
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}

                script: |
                  # 1. Đi tới thư mục dự án trên Droplet
                  cd /root/AnrealShop-backend
                  
                  # 2. Đăng nhập vào GHCR (để PULL image)
                  echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
                  
                  # 3. Kéo (pull) image mới nhất
                  docker-compose -f docker-compose-app.yml pull frontend-app
                  
                  # 4. Khởi động lại service 'backend-app' với image mới
                  docker-compose -f docker-compose-app.yml up -d --no-deps frontend-app
                  
                  # 5. (Tùy chọn) Xóa các image rác để tiết kiệm dung lượng
                  docker image prune -f
      
